---
# tasks file for Opam

- name: Set OPAMROOT to c:\opam
  win_environment:
    state: present
    name: OPAMROOT
    value: c:\opam
    level: machine

- name: Install Opam with WinGet
  win_command: winget install OCaml.opam --no-upgrade

- name: Run Opam Init
  win_command: opam init
